flex:
  version: 0.5.1
  workflows:
    setup-dependencies:
      command: pip3 install battenberg
    setup-repo:
      depends-on: setup-dependencies
      command: owner_name=fp-mt-test-org project_name=java-kotlin-lib-test-pTnSx ./.ngif/setup-repo.sh
    update-template:
      depends-on: setup-dependencies
      command: battenberg upgrade --no-input
    build:
      depends-on: setup-repo
      command: ./gradlew build
service:
  name: 'java-kotlin-lib-test-pTnSx'
